# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BingePodcast' do
  # Pods for BingePodcast
  use_frameworks!
	pod 'lottie-ios', '~> 3.1'
	pod 'SwiftGen', '~> 6.6.2'

  # Pods for BingePodcastTests
  target 'BingePodcastTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase'
	pod 'Firebase/Firestore'
  end

end


