# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'BingePodcast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'VBRRollingPit'
	pod 'lottie-ios', '~> 3.1'
	pod 'SwiftGen', '~> 6.0'


  # Pods for BingePodcast

  target 'BingePodcastTests' do
    inherit! :search_paths
    # Pods for testing
	pod 'Firebase'
  end

end


