name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: BingePodcast/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
      working-directory: BingePodcast
    - name: Build
      uses: mxcl/xcodebuild@v2
      with: 
        scheme: BingePodcast
        workspace: BingePodcast.xcworkspace
        working-directory: BingePodcast
        platform: iOS
