name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/cache@v3
      with:
        path: BingePodcast/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
    - name: CocoaPod Install
      run: pod install
      working-directory: BingePodcast
    - name: Build
      uses: mxcl/xcodebuild@v2
      with: 
        scheme: BingePodcast
        workspace: BingePodcast.xcworkspace
        working-directory: BingePodcast
        platform: iOS
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-
      - name: Exécuter les tests
        run: xcodebuild test -workspace BingePodcast/BingePodcast.xcworkspace  -scheme 'BingePodcast' -destination 'platform=iOS Simulator,OS=16.2,name=iPhone 12 Pro Max'
