# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: BingePodcast 
      run: |
        toto
        xcodebuild 
          -workspace "BingePodcast"
          -scheme "BingePodcast" \
          -archivePath $RUNNER_TEMP/bingePodcast.xcarchive \
          -sdk iphoneos \
          -configuration Debug \
          -destination generic/platform=iOS \
          -allowProvisioningUpdates \
          clean archive

  run_test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Testing
      uses: mxcl/xcodebuild@v2
      with: 
        scheme: BingePodcast
        workspace: BingePodcast.xcworkspace
        working-directory: BingePodcast
        platform: iOS
